### ISSUE TITLE
Nodemon should be an dependency

### ISSUE THREAD

**Issue by petetnt** [Versent/cfn-check#10]
Currently it's an `devDependency`, which `npm install -g` doesnt install, causing the script to fail with

```
Error: Cannot find module 'nodemon'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/cfn-check/bin/cfn-check.js:7:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by rowanu** [comment]
Whoops, thanks for letting me know.

**Comment by petetnt** [comment]
Thanks! 👍
